// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6B5LXtCUiJo1GqWn0MBI_Jflowx0bnw',
    appId: '1:1042514416337:web:5bb1f6e602e57d74f62bf0',
    messagingSenderId: '1042514416337',
    projectId: 'logs-edb2c',
    authDomain: 'logs-edb2c.firebaseapp.com',
    storageBucket: 'logs-edb2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQZ8teEcjxLf5JL7_n-pl6ntgg2xAe_V8',
    appId: '1:1042514416337:android:d054b41fa5d121bcf62bf0',
    messagingSenderId: '1042514416337',
    projectId: 'logs-edb2c',
    storageBucket: 'logs-edb2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUqu-4L-_BdXoY50l6YvkpGuUMwDWia-4',
    appId: '1:1042514416337:ios:9a48fedcdcee55a8f62bf0',
    messagingSenderId: '1042514416337',
    projectId: 'logs-edb2c',
    storageBucket: 'logs-edb2c.appspot.com',
    iosBundleId: 'com.example.logs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUqu-4L-_BdXoY50l6YvkpGuUMwDWia-4',
    appId: '1:1042514416337:ios:096d7f3b32cfb488f62bf0',
    messagingSenderId: '1042514416337',
    projectId: 'logs-edb2c',
    storageBucket: 'logs-edb2c.appspot.com',
    iosBundleId: 'com.example.logs.RunnerTests',
  );
}
